apiVersion: v1
kind: ConfigMap
metadata:
  name: my-crud-app-config
data:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.user }}:{{ .Values.postgresql.password }}@{{ .Values.postgresql.host }}:5432/{{ .Values.postgresql.database }}"