apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-crud-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-crud-app
  template:
    metadata:
      labels:
        app: my-crud-app
    spec:
      containers:
        - name: my-crud-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-crud-app-config
                  key: DATABASE_URL
          resources: {{ toYaml .Values.resources | nindent 12 }}