apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: 
          - python
          - app.py
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-crud-app-config
              key: DATABASE_URL
      restartPolicy: OnFailure