apiVersion: v1
kind: Service
metadata:
  name: my-crud-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: my-crud-app